# Generated by Django 3.2.2 on 2021-07-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatumApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='pref_max_age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref_min_age',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
